### ISSUE TITLE
Resize and scale intensity of image while maintaining aspect ratio

### ISSUE THREAD

**Issue by zivy** [SimpleITK/SimpleITKUtilities#4]
Resize and scale intensity of image, aspect ratio maintained with padding, useful for creating a uniform set of thumbnails from variable sized images, `resize_and_scale_uint8` in [this notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/21_Transforms_and_Resampling.ipynb).

**Comment by blowekamp** [comment]
The method should be further generalized with an option to preserve the aspect ratio and to select the output pixel type.

**Comment by zivy** [comment]
@blowekamp, not sure about your comment "option to preserve aspect ratio". 

The method says "aspect ratio maintained with padding". User selected pixel type for output is a valid change request. Below is the output of the notebook cell, hopefully this clarifies the aspect ratio feature:
![image](https://user-images.githubusercontent.com/338645/228592631-745c532d-cb20-45ae-b3e9-6108710075d8.png)

Let me know if this makes sense to you and then I'll just modify the output pixel type option as part of the changes between the notebook code and the python package.
